In [4]:
import numpy as np
import matplotlib.pyplot as plt
from scipy import linalg as la

In [5]:
# Q1

a = np.array([1, 0, 2, 3])

la.norm(a, 2)

3.7416573867739413

In [6]:
# Q3

A = np.random.rand(20, 20)
b = np.random.rand(20, 1)

np.linalg.solve(A, b)

array([[ 4.09413026],
       [-4.35771995],
       [-0.29096309],
       [-2.68331998],
       [-4.95638805],
       [ 4.14007972],
       [ 2.23042026],
       [-4.19218166],
       [ 0.38823774],
       [-9.20300419],
       [ 1.37839435],
       [-0.03563777],
       [ 8.78354501],
       [ 5.44246463],
       [ 2.9926909 ],
       [ 7.13635481],
       [ 0.13169136],
       [-0.38848337],
       [-3.23171101],
       [-1.28693344]])

In [7]:
# Q5
A = np.random.rand(4, 4)

P, L, U = la.lu(A)

In [8]:
print(L)
print(U)

[[1.         0.         0.         0.        ]
 [0.03883795 1.         0.         0.        ]
 [0.49073537 0.36824087 1.         0.        ]
 [0.03347682 0.86782698 0.09226226 1.        ]]
[[ 0.53703954  0.22557484  0.31038523  0.11538979]
 [ 0.          0.84003565  0.33675943  0.15661962]
 [ 0.          0.          0.2309708   0.19955364]
 [ 0.          0.          0.         -0.09968115]]


In [9]:
# Q6
Q, R = la.qr(A)

In [10]:
R

array([[-0.59885334, -0.43881495, -0.52347323, -0.24896785],
       [ 0.        , -1.13917738, -0.51622164, -0.20053616],
       [ 0.        ,  0.        , -0.19948488, -0.18212908],
       [ 0.        ,  0.        ,  0.        , -0.07632244]])

In [14]:
(Q@la.inv(Q))

array([[ 1.00000000e+00,  0.00000000e+00,  1.38777878e-17,
        -1.38777878e-17],
       [ 0.00000000e+00,  1.00000000e+00,  2.77555756e-17,
         4.16333634e-17],
       [-4.85722573e-17, -8.32667268e-17,  1.00000000e+00,
        -2.77555756e-17],
       [ 1.38777878e-17, -9.71445147e-17, -1.38777878e-17,
         1.00000000e+00]])

In [11]:
la.inv(Q)==Q.T

array([[ True, False, False, False],
       [False, False, False,  True],
       [False, False, False, False],
       [False, False, False,  True]])

In [17]:
# Q7
A = np.random.rand(5, 5)
v = np.random.rand(5, 1)

mu = [1, 2]

while abs(mu[-1]-mu[-2]) > 0.05:
    
    u = A@v
    mu.append(la.norm(u, 2))
    
    v = u/mu[-1]
    

mu

In [18]:
mu

[1,
 2,
 1.3673716814612755,
 2.339520235504077,
 2.5560699594566954,
 2.5736255407738886]

In [19]:
v

array([[0.58185149],
       [0.42645445],
       [0.38506563],
       [0.33501399],
       [0.46805505]])

In [20]:
# Q8

def peig(A, tol):
    
    v = np.random.rand(A.shape[1], 1)
    mu = []
    
    for i in range(2):
        u = A@v
        mu.append(la.norm(u, 2))

        v = u/mu[-1]
        
    while abs(mu[-1] - mu[-2])> tol:
        
        u = A@v
        mu.append(la.norm(u, 2))

        v = u/mu[-1]
        
    return (mu[-1], v)

In [21]:
# Q9

def invpeig(A, tol):
    
    v = np.random.rand(A.shape[1], 1)
    mu = []
    
    for i in range(2):
        u = la.inv(A)@v
        mu.append(la.norm(u, 2))

        v = u/mu[-1]
        
    while abs(mu[-1] - mu[-2])> tol:
        
        u = la.inv(A)@v
        mu.append(la.norm(u, 2))

        v = u/mu[-1]
        
    return (1/mu[-1], v)

In [ ]:
# Q10

def qreigs(A, tol):
    
    def get_eigen_values(A):
        
        eigen_values = []
        
        for i in range(A.shape[0]):
            eigen_values.append(A[i, i])
        
        return np.array(eigen_values)
    
    eig1 = get_eigen_values(A)
    Q, R = la.qr(A)
    A = R@Q
    eig2 = get_eigen_values(A)
    
    while la.norm((eig1-eig2), 2) > tol:
        
        Q, R = la.qr(A)
        eig1 = get_eigen_values(A)
        
        A = R@Q
        eig2 = get_eigen_values(A)
        
    
    return (eig1+eig2)/2
    